### PR TITLE
feature(imports): analyze imports and determine name of imported entity

### PR DESCRIPTION
**Pull request by thekip**
fixes: https://github.com/lingui/swc-plugin/issues/9

### CODE REVIEW

**Comment by thekip** [comment]
Also re-organized and updated deps, and it seems it helps to support next 12 as well

**Review by andrii-bodnar — APPROVED** [review]

**Comment by andrii-bodnar** [comment]
@thekip thank you! 🚀

**Comment by mikkelsl** [comment]
You are a fucking champion

**Comment by thekip** [comment]
Author of swc is fucking champion, i'm just learning  👨🏻‍🎓

**Pull request merged**
