### PR TITLE
Next 15 support (swc_core@0.106.3)

### PR DESCRIPTION
**Pull request by datagutt**
This bumps swc_core to 0.106.3.
This is tested with Next 15.0.0

### CODE REVIEW

**Comment by BANG88** [comment]
‌‌Hello, may I ask if this can be merged? Thank you very much.

**Comment by datagutt** [comment]
Not sure why the "test publish" action is failing, as building does seem to work locally

**Comment by BANG88** [comment]
‌‌Waiting for upgrade Next15 😄

**Comment by timofei-iatsenko** [comment]
Could not find this version (and previous as well) in the compatibility site, created the issue https://github.com/swc-project/website/issues/273

**Comment by datagutt** [comment]
Yeah, I noticed the compatibility site not updating after a certain canary version.
I ended up manually checking the package.json for Next.

**Comment by timofei-iatsenko** [comment]
I reverted rust toolchain, have no idea why it was bumped. It seems it builds with existing version without issue.

**Comment by datagutt** [comment]
swc_core at some point bumped the rust toolchain, so i did as well.
This according to the https://github.com/lingui/swc-plugin/blob/main/CONTRIBUTING.md#rust-version documentation

**Comment by datagutt** [comment]
SWC uses nightlies internally, but it does seem that 2024-07-21 and 1.80 is pretty much the same release
https://github.com/swc-project/swc/pull/9319

**Comment by andrii-bodnar** [comment]
Available in [4.1.0](https://github.com/lingui/swc-plugin/releases/tag/4.1.0).

**Pull request merged**
