### PR TITLE
feature: split js / jsx macro

### PR DESCRIPTION
**Pull request by thekip**
port: https://github.com/lingui/js-lingui/pull/1883

closes: https://github.com/lingui/swc-plugin/issues/85

### CODE REVIEW

**Comment by yunsii** [comment]
image

It still not work with `@lingui/swc-plugin@5.0.0-next.0`, commit: https://github.com/yunsii/lingui-examples-nextjs-swc-1797/commit/5573547651363d5f7d03bb4be4a62aaaa70d5ed8

**Comment by thekip** [comment]
But this is a diffrent issue, looks like a version misalignment between next-swc/swc core version and lingui plugin version.

**Comment by yunsii** [comment]
We are still use next 13.4.12, is it possible to support it?

**Comment by thekip** [comment]
this is an upstream issue, swc plugins doesn't have a semver compatibility. We could not publish changes to the plugin using previous version of swc-core. But you can compile plugin with whatever version of swc-core you need and store wasm  binary in your repo.  There is a comprehensive manual how to do that in plugin's contribution guide.

**Comment by yunsii** [comment]
Thanks, I will try it later.

**Comment by Yidoon** [comment]
> this is an upstream issue, swc plugins doesn't have a semver compatibility. We could not publish changes to the plugin using previous version of swc-core. But you can compile plugin with whatever version of swc-core you need and store wasm binary in your repo. There is a comprehensive manual how to do that in plugin's contribution guide.

It doesn't work :( , I replace the swc_core version to 0.79.28 , but get a lot of erros when I run cargo build-wasi --release.👇
image

this is rust show command result in my device 
image

see this commit(I just replace the swc-core version from  0.90.35 to 0.79.28 in the Cargo.toml file): [swc-core version](https://github.com/Yidoon/swc-plugin-replace-swc-core-version)

**Comment by thekip** [comment]
Because there are breaking changes between these two swc-core versions.

You need to revert changes from this pull requests to make it work with 0.79.28 version: 

https://github.com/lingui/swc-plugin/pull/91
https://github.com/lingui/swc-plugin/pull/79

Simply revert content of the rust files, no need to touch examples, readme, etc

**Pull request merged**
